version: 2

sources:
  - name: raw
    database: ceren-data0426
    schema: gz_raw_data1
    tables:
      - name: sales        
        identifier: raw_gz_sales
        description: "Greenweez company-Staging model for sales data."
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"        
        columns:
          - name: date_date
            description: "Date of purchase"
            tests: 
              - not_null
          - name: orders_id
            description: "ID of the orders"
            tests: 
              - not_null
          - name: pdt_id
            description: "ID of the product"
            tests: 
              - not_null   
          - name: revenue
            description: "Gross revenue amount. Currency: USD"
            tests: 
              - not_null  
          - name: quantity
            description: "The number of units sold"
            tests: 
              - not_null      

      - name: product       
        identifier: raw_gz_product
        description: "Greenweez company-Staging model for product data."
        columns:
          - name: products_id
            description: "Primary key for products"
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE 
            description: "Raw purchase price string."
            tests: 
              - not_null            

      - name: ship   
        identifier: raw_gz_ship
        description: "Greenweez company-Staging model for shipping data."
        columns:
          - name: orders_id 
            description: "Primary key for shipping"
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "Shipping and handling fees."
            tests: 
              - not_null    
          - name: logCost
            description: "Total logistics cost."
            tests: 
              - not_null    
          - name: ship_cost
            description: "Actual shipping cost."
            tests: 
              - not_null